services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: PAYMENT_NUMBER
        sync: false
      - key: GROUP_LINK
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: PORT
        value: 8080
